clinic/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("schedule", views.get_schedule, name="schedule"),
    path("contacts", views.get_contacts, name="contacts"),
    path("vacancy", views.get_vacancy, name="vacancy"),
    path("staff", views.DoctorList.as_view(), name="staff"),
    path("reviews/<slug:doctor_slug>", views.DoctorReviews.as_view(), name="reviews"),
    path("making-an-appointment", login_required(views.AppointmentForm.as_view()), name="making-an-appointment"),
    path("record", views.AppointmentForm.as_view(), name="record"),
    path("registration", views.get_registration_form, name="registration"),
    path("register", views.validate_registration, name="register"),
    path("send_contract_num", views.send_contract_num, name="send_contract_num"),
    path("user-cabinet", login_required(views.UserCabinet.as_view()), name="user-cabinet"),
    path("sendReview", views.SendReview.as_view(), name="send_review"),
    path("<str:doctor_img_name>", views.index, name="index")
]

clinic/models.py
# Create your models here.
from django.core.exceptions import ValidationError
import textwrap
from django.http import QueryDict
from django.contrib.auth.models import User
from django.urls import reverse
from django.db import models


class DoctorCategory(models.Model):
    name = models.CharField(max_length=25)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категорія доктора"
        verbose_name_plural = "Категорії докторів"
        ordering = ["id"]


class Doctor(models.Model):
    name = models.CharField(max_length=15)
    lastname = models.CharField(max_length=30)
    patronymic = models.CharField(max_length=20)
    category = models.ForeignKey(DoctorCategory, on_delete=models.SET_NULL, null=True)
    work_start_date = models.DateField()
    image_name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, blank=True, null=True, verbose_name="url")

    def __str__(self):
        return f"{self.lastname} {self.name} {self.patronymic}"

    class Meta:
        verbose_name = "Доктор"
        verbose_name_plural = "Доктори"
        ordering = ("-work_start_date",)

    def get_absolute_url(self):
        return reverse("reviews", kwargs={"doctor_slug": self.slug})

    def full_name(self):
        return f"{self.lastname} {self.name} {self.patronymic}"


class DoctorPhoneNumber(models.Model):
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    phone_number_value = models.CharField(max_length=20)

    def __str__(self):
        return f"Doctor: {self.doctor.lastname} {self.doctor.name}, phone: {self.phone_number_value}"

    class Meta:
        verbose_name = "Телефонний номер доктора"
        verbose_name_plural = "Телефонні номери докторів"
        ordering = ("doctor__id",)


class Patient(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    doctor = models.ForeignKey(to=Doctor, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=15)
    lastname = models.CharField(max_length=30)
    patronymic = models.CharField(max_length=30)
    contract_num = models.CharField(max_length=10)
    phone_number = models.CharField(max_length=15)
    street_type = models.CharField(max_length=10)
    street_name = models.CharField(max_length=40)
    house_number = models.CharField(max_length=4)
    flat_number = models.CharField(max_length=4)
    post_index = models.IntegerField()

    def __str__(self):
        return f"{self.lastname} {self.name}"

    def create_patient_from_dict(self, user: User, dct: QueryDict):
        self.user = user
        self.doctor = Doctor.objects.get(pk=int(dct["doctor_choice"]))
        self.name = dct["name"]
        self.lastname = dct["lastname"]
        self.patronymic = dct["patronymic"]
        self.contract_num = dct["contract_num"]
        self.phone_number = dct["phone_number"]
        self.street_type = dct["street_type"]
        self.street_name = dct["street_name"]
        self.house_number = dct["house_number"]
        self.flat_number = dct["flat_number"]
        self.post_index = dct["post_index"]
        self.save(force_insert=True)

    class Meta:
        verbose_name = "Пацієнт"
        verbose_name_plural = "Пацієнти"


class Review(models.Model):
    doctor = models.ForeignKey(to=Doctor, on_delete=models.CASCADE)
    patient = models.ForeignKey(to=Patient, on_delete=models.CASCADE, null=True)
    text = models.CharField(max_length=1000)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return textwrap.shorten(self.text, 50)

    def get_absolute_url(self):
        return reverse("reviews", kwargs={"doctor_slug": self.doctor.slug})

    class Meta:
        verbose_name = "Відгук"
        verbose_name_plural = "Відгуки"
        ordering = ("created_at",)


class Recording(models.Model):
    person = models.ForeignKey(Patient, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    health_complaint = models.CharField(max_length=255)

    def __str__(self):
        return f"From: {self.person.name}"

    class Meta:
        verbose_name = "Запис на прийом"
        verbose_name_plural = "Записи на прийом"
        ordering = ("-created_at",)


class Cabinet(models.Model):
    cabinet_no = models.IntegerField(primary_key=True)
    cabinet_name = models.CharField(max_length=128)
    cabinet_description = models.CharField(max_length=255)

    def __str__(self):
        return f"Cabinet name: {self.cabinet_name}"

    class Meta:
        verbose_name = "Кабінет"
        verbose_name_plural = "Кабінети"
        ordering = ("-cabinet_no",)


class Schedule(models.Model):
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    start_datetime = models.DateTimeField()
    end_datetime = models.DateTimeField()
    cabinet = models.ForeignKey(Cabinet, null=True, blank=True, on_delete=models.SET_NULL)
    recording = models.OneToOneField(Recording, null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        if not self.recording:
            return f"Doctor: {self.doctor.lastname} {self.doctor.name}, date: {self.start_datetime.date()}"
        return f"Doctor: {self.doctor.lastname} {self.doctor.name}, date: {self.start_datetime.date()}, " \
               f"patient: {self.recording.person}"

    class Meta:
        verbose_name = "Графік роботи"
        verbose_name_plural = "Графіки роботи"
        ordering = ("-start_datetime",)

    def clean(self):
        if self.recording:
            raise ValidationError("Цей запис вже зайнято. Оберіть інший час!")

    def __lt__(self, other):
        return self.start_datetime < other.start_datetime

clinic/forms.py
from django import forms
from clinic.models import Review
from django.utils.translation import gettext_lazy as _


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ["doctor", "patient", "text"]
        widgets = {
            "doctor": forms.HiddenInput(),
            "patient": forms.HiddenInput(),
            "text": forms.Textarea(attrs={"class": "review-textarea",
                                          "id": "review-text",
                                          "name": "review_text",
                                          "placeholder": _("Введіть текст відгуку...")})
        }

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.fields["text"].label = "Текст відгуку"

clinic/views.py
import datetime

from django.db import IntegrityError
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, View
from .forms import ReviewForm

from clinic.models import Doctor, Patient, Recording, Schedule
from django.http import HttpResponse, HttpResponseRedirect
from django.core.exceptions import ValidationError
from clinic.contract import get_rand_contract_num
from clinic.turbosms import TurboSMSMessage
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
import json


# Create your views here.
def index(request, doctor_img_name="default_photo"):
    return render(request, template_name="clinic/index.html", context={"doctor_img_name": doctor_img_name})


def get_schedule(request):
    return render(request, template_name="clinic/pages/schedule-work.html")


def get_contacts(request):
    return render(request, template_name="clinic/pages/contacts.html")


def get_vacancy(request):
    return render(request, template_name="clinic/pages/vacancy.html")


def quiz(request):
    return render(request, template_name="clinic/pages/", context={"lang": request.LANGUAGE_CODE})


class DoctorList(ListView):
    model = Doctor
    template_name = "clinic/pages/staff.html"
    context_object_name = "doctors"


class DoctorReviews(DetailView):
    model = Doctor
    template_name = "clinic/pages/reviews.html"
    context_object_name = "doctor"
    slug_url_kwarg = "doctor_slug"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated and not self.request.user.is_superuser:
            context["form"] = ReviewForm(initial={
                "doctor": self.get_object(),
                "patient": self.request.user.patient
            })
        return context


class SendReview(CreateView):
    model = Doctor
    form_class = ReviewForm
    template_name = "clinic/pages/reviews.html"
    context_object_name = "doctor"
    slug_url_kwarg = "doctor_slug"


class AppointmentForm(View):
    def get(self, request):
        try:
            doctor = Patient.objects.get(user=request.user).doctor
            appointments = sorted(doctor.schedule_set.filter(recording=None,
                                                             start_datetime__gt=datetime.datetime.now()))
            return render(request,
                          template_name="clinic/pages/making-an-appointment.html",
                          context={"doctor": doctor,
                                   "appointments": appointments,
                                   "app_dates": get_appointments_dates(appointments)})
        except Patient.DoesNotExist:
            doctor_err = _(
                "Помилка: не знайдено лікаря, із яким узгоджено контракт. Перевірте свій акаунт або перезавантажте сторінку!")
            return render(request,
                          template_name="clinic/pages/making-an-appointment.html",
                          context={"doctor_err": doctor_err})

    def post(self, request):
        doctor = Doctor.objects.get(pk=request.POST["appointment_doctor_pk"])
        recording = Recording(person=request.user.patient,
                              health_complaint=request.POST["appointment_complaint"])
        recording.save()
        time = get_full_time(request.POST["appointment_time"]) if request.LANGUAGE_CODE.lower() == "en" else \
            request.POST["appointment_time"]
        dt_tm = datetime.datetime.strptime(request.POST["appointment_date"] + "T" + time, "%d.%m.%YT%H:%M")
        try:
            schedule = Schedule.objects.get(doctor=doctor,
                                            start_datetime=dt_tm)
            schedule.recording = recording
            schedule.save()
            appointments = sorted(doctor.schedule_set.filter(recording=None,
                                                             start_datetime__gt=datetime.datetime.now()))
            return render(request,
                          template_name="clinic/pages/making-an-appointment.html",
                          context={"doctor": doctor,
                                   "appointments": appointments,
                                   "app_dates": get_appointments_dates(appointments),
                                   "success_message": _(
                                       "Запис на прийом успішно виконано! За необхідністю можете записатися ще")})
        except ValidationError:
            err = "Помилка: цей час вже зайнято, перезавантажте сторінку та оберіть інший"
            appointments = sorted(doctor.schedule_set.filter(recording=None,
                                                             start_datetime__gt=datetime.datetime.now()))
            return render(request,
                          template_name="clinic/pages/making-an-appointment.html",
                          context={"doctor": doctor,
                                   "appointments": appointments,
                                   "app_dates": get_appointments_dates(appointments),
                                   "err": err})


def get_registration_form(request):
    doctors = Doctor.objects.all()
    return render(request, template_name="registration/registration.html", context={"doctors": doctors})


def send_contract_num(request):
    contract_num = get_rand_contract_num()
    print(contract_num)
    ts_message = TurboSMSMessage(contract_num=contract_num, recipients=[request.POST["phone_number"]])
    ts_message.send()
    return HttpResponse(contract_num)


def validate_registration(request):
    try:
        user = User.objects.create_user(username=request.POST["phone_number"],
                                        password=request.POST["contract_num"],
                                        first_name=request.POST["name"],
                                        last_name=request.POST["lastname"])
        user.save()
        Patient().create_patient_from_dict(user, request.POST)
        return HttpResponseRedirect(redirect_to="/index")
    except IntegrityError:
        doctors = Doctor.objects.all()
        return render(request,
                      template_name="registration/registration.html",
                      context={"user_already_exists": True,
                               "doctors": doctors})


def get_full_time(tm: str) -> str:
    time_lst = tm.split()
    time = time_lst[0].split(":")
    if time_lst[1] == "a.m." and time[0] == "12":
        return "00:" + time[1]
    elif time_lst[1] == "a.m.":
        return time_lst[0]
    elif time_lst[1] == "p.m." and time[0] == "12":
        return "12:" + time[1]
    return str(int(time[0]) + 12) + ":" + time[1]


def get_appointments_dates(appointments) -> list[datetime.datetime]:
    app_dates = []
    for app in appointments:
        app_date = app.start_datetime
        if app_date.date() not in map(lambda dt_tm: dt_tm.date(), app_dates):
            app_dates.append(app_date)
    return list(map(lambda dt_tm: dt_tm.strftime("%d.%m.%Y"), app_dates))


class UserCabinet(ListView):
    model = Recording
    template_name = "clinic/pages/user-cabinet.html"
    context_object_name = "appointments"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["current_date"] = datetime.datetime.now()
        return context

    def get_queryset(self):
        if self.request.user.is_authenticated:
            return self.model.objects.filter(person__user=self.request.user,
                                             schedule__start_datetime__gte=datetime.datetime.now() - datetime.timedelta(
                                                 days=5)).order_by("schedule__start_datetime")

clinic/templates/clinic/pages/contacts.html
{% extends "clinic/base.html" %}
{% load static %}
{% load i18n %}

{% block head %}
    <title>{% trans 'Контакти' %}</title>
    <link rel="stylesheet" href="{% static 'css/contacts.css' %}">
{% endblock %}

{% block header_contacts %}
    <a class="inner-btn disabled" href="{% url 'contacts' %}">{% trans 'Контакти' %}</a>
{% endblock %}

{% block mobile-menu_contacts %}
    <a class="btn disabled" href="{% url 'contacts' %}">{% trans 'Контакти' %}</a>
{% endblock %}

{% block language_href %}
    href="/{{ language.code }}/contacts"
{% endblock %}

{% block content %}
    <div class="title-box">
        <h2>{% trans 'Контакти' %}</h2>
    </div>
    <section class="contacts-container">
        <div class="contacts">
            <article class="inner-contact" id="phones">
                <h4 class="subtitle">{% trans 'Телефони:' %}</h4><br>
                <a class="link subtitle-text" id="phone_1" href="tel: +380665483699">+38066-548-36-99</a>,<br>
                <a class="link subtitle-text" id="phone_2" href="tel: +380975483699">+38097-548-36-99</a>
            </article>
            <article class="inner-contact" id="address">
                <h4 class="subtitle">{% trans 'Адреса:' %}</h4>
                <span class="subtitle-text">{% trans 'вул. Тюрінська, 96' %}</span>
            </article>
            <article class="inner-contact" id="email">
                <h4 class="subtitle">Email:</h4><br>
                <span class="subtitle-text" id="main_doctor">{% trans 'Головний лікар Мєтіла Євген Дмитрович:' %}
                    <a class="link" href="mailto: polyclinic@ukr.net">polyclinic@ukr.net</a>
                    </span><br>
                <span class="subtitle-text" id="pers_dep">{% trans 'Відділ по роботі з персоналом:' %}
                        <a class="link" href="mailto: kh_pers@ukr.net">kh_pers_496@ukr.net</a>
                    </span><br>
                <span class="subtitle-text" id="ad_dep">{% trans 'Відділ реклами:' %}
                        <a class="link" href="mailto: kh_ad_496@ukr.net">kh_ad_496@ukr.net</a>
                    </span><br>
                <span class="subtitle-text" id="common_quest">{% trans 'Загальні питання:' %}
                        <a class="link" href="mailto: kh_cl_496@ukr.net">kh_cl_496@ukr.net</a>
                    </span>
            </article>
        </div>
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2564.724782613777!2d36.29115571589929!3d49.99776912775927!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4127a0a8db6a8ead%3A0x79e80c7b9c345863!2z0YPQuy4g0KLRjtGA0LjQvdGB0LrQsNGPLCA5Niwg0KXQsNGA0YzQutC-0LIsINCl0LDRgNGM0LrQvtCy0YHQutCw0Y8g0L7QsdC70LDRgdGC0YwsIDYxMDAw!5e0!3m2!1sru!2sua!4v1666687058008!5m2!1sru!2sua"
                width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"
                referrerpolicy="no-referrer-when-downgrade"></iframe>
    </section>
{% endblock %}

clinic/templates/clinic/pages/contract_num.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

clinic/templates/clinic/pages/login.html
{% extends "clinic/base.html" %}
{% load static %}
{% load i18n %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <title>{% trans 'Харківська районна лікарня №496' %}</title>
{% endblock %}

{% block content %}
    <div class="registration-form-wrapper">
        <div class="registration-form">
            <div class="registration-form-title">
                <h3>Авторизація</h3>
            </div>
            <form class="form-data" method="post" action="{% url 'validate_login' %}">
                {% csrf_token %}
                <div class="user-info">
                    <div class="user-info__first">
                        <div class="field-block">
                            <label for="login-name">Ім'я користувача</label>
                            <input type="text" id="login-name" name="lastname" required>
                        </div>
                    </div>
                    <div class="user-info__second">
                        <div class="field-block">
                            <label for="login-contract-num">Номер контракту</label>
                            <input type="text" id="login-contract-num" name="name" required>
                        </div>
                    </div>
                    <div class="form-actions">
                        <div class="button-block">
                            <input type="submit" value="Увійти">
                        </div>
                        <div class="button-block">
                            <input type="reset" value="Очистити все">
                        </div>
                    </div>
                </div>
            </form>
            <div class="no-account">
                <span class="no-account__text">Ще немає акаунту? <a href="/registration">Створіть його</a></span>
            </div>
        </div>
    </div>
{% endblock %}

clinic/templates/clinic/pages/reviews.html
{% extends "clinic/base.html" %}
{% load static %}
{% load i18n %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/reviews.css' %}">
    <title>{% trans 'Відгуки' %}</title>
{% endblock %}


{% block language_href %}
    href="/{{ language.code }}/reviews/{{ doctor.slug }}"
{% endblock %}


{% block content %}
    <div class="title-box">
        <h2>{% trans 'Інформація про лікаря' %}</h2>
    </div>
    {% load clinic_extras %}
    <div class="doctor-wrapper">
        <div class="doctor-info">
            <img srcset="{% get_static_prefix %}img/250w/{{ doctor.image_name }}.png 250w,
                             {% get_static_prefix %}img/200w/{{ doctor.image_name }}.png 200w,
                             {% get_static_prefix %}img/150w/{{ doctor.image_name }}.png 150w"
                 sizes="(max-width: 1024px) 150px,
                        (max-width: 1452px) 200px,
                        250px"
                 src="{% get_static_prefix %}img/250w/{{ doctor.image_name }}.png" alt="">
            <div class="doctor-description">
                <h3 class="header">{{ doctor.lastname }} {{ doctor.name }} {{ doctor.patronymic }}</h3>
                <div class="prof-info">
                    <span class="category-info">{{ doctor.category.name }} {% trans 'кваліфікаційна категорія' %}</span>
                    <div class="work-experience">{% trans 'Стаж' %}: {{ doctor.work_start_date|years_to_now }}
                    {% get_current_language as CURRENT_LANGUAGE %}
                            {% if CURRENT_LANGUAGE == "uk" %}
                                {% uk_pluralize doctor.work_start_date|years_to_now "рік,роки,років" %}
                            {% else %}
                                {% blocktrans count years=doctor.work_start_date|years_to_now %}
                                    year
                                {% plural %}
                                    years
                                {% endblocktrans %}
                            {% endif %}
                    </div>
                </div>
                <a href="" class="feedback_btn">{% trans 'Залишити відгук' %}</a>
            </div>
        </div>
    </div>
    <div class="title-box">
        <h2>{% trans 'Відгуки' %}</h2>
    </div>
    <div class="reviews">
        <form class="reviews__menu">
            <div class="reviews__menu__title">{% trans 'Налаштування відгуків' %}</div>
            <div class="reviews__menu__elems">
                <div class="menu__elem">
                    <label for="background" class="menu__option__title">{% trans 'Фон' %}</label>
                    <select name="options" id="background">
                        <option value="">--{% trans 'Оберіть колір фону' %}--</option>
                        <option value="red">{% trans 'Червоний' %}</option>
                        <option value="blue">{% trans 'Синій' %}</option>
                        <option value="green">{% trans 'Зелений' %}</option>
                        <option value="yellow">{% trans 'Жовтий' %}</option>
                    </select>
                </div>
                <div class="menu__elem">
                    <label for="font-size" class="menu__option__title">{% trans 'Розмір шрифта' %}</label>
                    <select name="options" id="font-size">
                        <option value="">--{% trans 'Оберіть розмір шрифта' %}--</option>
                        <option value="0.4em">0.4em</option>
                        <option value="0.6em">0.6em</option>
                        <option value="0.8em">0.8em</option>
                        <option value="1em">1em</option>
                        <option value="1.2em">1.2em</option>
                        <option value="1.5em">1.5em</option>
                    </select>
                </div>
                <div class="menu__elem">
                    <label for="font-type" class="menu__option__title">{% trans 'Тип шрифта' %}</label>
                    <select name="options" id="font-type">
                        <option value="">--{% trans 'Оберіть тип шрифту' %}--</option>
                        <option value="serif">Serif</option>
                        <option value="sans-serif">Sans-serif</option>
                    </select>
                </div>
                <div class="menu__elem">
                    <input type="reset" id="default-button" value="{% trans 'За замовченням' %}">
                </div>
            </div>
        </form>
        {% if not doctor.review_set.all %}
            <p class="no-reviews">{% trans 'Немає жодного відгуку' %}</p>
        {% else %}
            {% for review in doctor.review_set.all reversed %}
                <div class="review">
                    <blockquote class="account">
                        <cite>{{ review.patient.lastname }} {{ review.patient.name }}</cite>
                        <time datetime="{{ review.created_at }}">{% frmt_datetime review.created_at "%d.%m.%Y %H:%M" %}</time>
                    </blockquote>
                    <p class="comment">{{ review.text }}</p>
                </div>
            {% endfor %}
        {% endif %}
    </div>
    <div class="review-blank-wrapper hidden">
        {% if form %}
            {% if user.patient.doctor == doctor %}
                <div class="review-blank">
                    <div class="close-block">
                        <a href="" class="close-button">X</a>
                    </div>
                    <form method="post" action="{% url 'send_review' %}" class="blank">
                        {% csrf_token %}
                        {{ form.doctor }}
                        {{ form.patient }}
                        <div class="inner-box" id="review-box">
                            <label for="review_text">{{ form.text.label }}</label>
                            {{ form.text }}
                        </div>
                        <div class="inner-box" id="submit-button-wrapper">
                            <input type="submit" class="submit-review-button" value="{% trans 'Відправити' %}">
                        </div>
                    </form>
                </div>
            {% else %}
                <div class="err-blank">
                    <div class="close-block">
                        <a href="" class="close-button">X</a>
                    </div>
                    <h2>{% trans 'Для того, щоб залишати відгуки для цього лікаря, необхідно укласти із ним контракт' %}</h2>
                </div>
            {% endif %}
        {% else %}
            <div class="err-blank">
                <div class="close-block">
                    <a href="" class="close-button">X</a>
                </div>
                <h2>{% trans 'Залишати відгуки можуть тільки аутентифіковані користувачі' %} <a href="{% url 'login' %}?next={{ request.path }}"
                                                                                style="text-decoration: none">{% trans 'Увійти' %}</a>
                </h2>
            </div>
        {% endif %}
    </div>
{% endblock %}
{% block scripts %}
    <script src="{% static 'js/reviews.js' %}" type="module"></script>
{% endblock %}

clinic/templates/clinic/pages/staff.html
{% extends 'clinic/base.html' %}
{% load static %}
{% load i18n %}
{% load clinic_extras %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/staff.css' %}">
    <title>{% trans 'Наші лікарі' %}</title>
{% endblock %}

{% block header_staff %}
    <a class="btn disabled" href="{% url 'staff' %}">{% trans 'Наші лікарі' %}</a>
{% endblock %}

{% block mobile-menu_staff %}
    <a class="btn disabled" href="{% url 'staff' %}">{% trans 'Наші лікарі' %}</a>
{% endblock %}

{% block language_href %}
    href="/{{ language.code }}/staff"
{% endblock %}

{% block content %}
    <div class="title-box">
        <h2>{% trans 'Наші лікарі' %}</h2>
    </div>
    <div class="doctors">
        {% for doctor in doctors %}
            <div class="block-doctor">
                <div class="photo">
                    <img srcset="{% get_static_prefix %}img/250w/{{ doctor.image_name }}.png 250w,
                                 {% get_static_prefix %}img/200w/{{ doctor.image_name }}.png 200w,
                                 {% get_static_prefix %}img/150w/{{ doctor.image_name }}.png 150w"
                         sizes="(max-width: 768px) 150px,
                                (max-width: 1300px) 200px,
                                250px"
                         src="{% get_static_prefix %}img/250w/{{ doctor.image_name }}.png" alt="">
                </div>
                <div class="full-description">
                    <h5 class="description-header">{{ doctor.lastname }} {{ doctor.name }} {{ doctor.patronymic }}</h5>
                    <div class="description-block">
                        <p class="description">{{ doctor.category.name }} {% trans 'кваліфікаційна категорія' %}<br>
                            {% trans 'Номери телефону' %}:
                            {% for phone_obj in doctor.doctorphonenumber_set.values %}
                                {{ phone_obj.phone_number_value }}{% if not forloop.last %},{% endif %}
                            {% endfor %}<br>
                        </p>
                        <p class="experience-description">{% trans 'Стаж роботи' %}: {{ doctor.work_start_date|years_to_now }}
                            {% get_current_language as CURRENT_LANGUAGE %}
                            {% if CURRENT_LANGUAGE == "uk" %}
                                {% uk_pluralize doctor.work_start_date|years_to_now "рік,роки,років" %}
                            {% else %}
                                {% blocktrans count years=doctor.work_start_date|years_to_now %}
                                    year
                                {% plural %}
                                    years
                                {% endblocktrans %}
                            {% endif %}
                        </p>
                        <a class="doctor-btn"
                           href="{% url 'reviews' doctor_slug=doctor.slug %}">{% trans 'Докладніше...' %}</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}
<footer>
    <div class="footer-content">
        <h3>Харківська районна клініка</h3>
        <p>Комунальне некомерційне підприємство "Міська поліклініка № 496" Харківської міської ради</p>
        <ul class="socials">
            <li>
                <a href="https://facebook.com"><i class="fa fa-facebook"></i></a>
            </li>
            <li>
                <a href="https://instagram.com"><i class="fa fa-instagram"></i></a>
            </li>
            <li>
                <a href="https://twitter.com"><i class="fa fa-twitter"></i></a>
            </li>
            <li>
                <a href="https://youtube.com"><i class="fa fa-youtube"></i></a>
            </li>
        </ul>
    </div>
    <div class="footer-bottom">
        <p>&copy; 2008-2022</p>
        <p>Міністерство охорони здоров'я</p>
    </div>
</footer>
<script src="https://kit.fontawesome.com/c3664bd84b.js" crossorigin="anonymous"></script>
<script src="../js/header.js"></script>